Adding a test which check that a ServerConfigurationError is raised when the file 'emailSettings.init' is missing in the server.
Now it fails because a ConfigParser exception is wrongly raised:
    ConfigParser.NoSectionError: No section: 'email'
that is confusing